CREATE SCHEMA EVIDENTIRANJE;
CREATE TABLE EVIDENTIRANJE.KORISNIK(
korisnik_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
ime VARCHAR(50) NOT NULL,
prezime VARCHAR(50) NOT NULL,
kontakt_broj INTEGER,
napomena VARCHAR(200),
datum_kreiranja DATE NOT NULL,
CONSTRAINT korisnik_id_pk PRIMARY KEY (korisnik_id)
);

CREATE TABLE EVIDENTIRANJE.VRSTA(
vrsta_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
naziv VARCHAR(100) NOT NULL,
CONSTRAINT vrsta_id_pk PRIMARY KEY (vrsta_id)
);

INSERT INTO EVIDENTIRANJE.VRSTA (naziv) VALUES ('Critical');
INSERT INTO EVIDENTIRANJE.VRSTA (naziv) VALUES ('Major');
INSERT INTO EVIDENTIRANJE.VRSTA (naziv) VALUES ('Minor');

CREATE TABLE EVIDENTIRANJE.KATEGORIJA(
kategorija_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
naziv VARCHAR(100) NOT NULL,
CONSTRAINT kategorija_id_pk PRIMARY KEY (kategorija_id)
);

INSERT INTO EVIDENTIRANJE.KATEGORIJA (naziv) VALUES ('MREŽNI');
INSERT INTO EVIDENTIRANJE.KATEGORIJA (naziv) VALUES ('POSLUŽITELJSKI');
INSERT INTO EVIDENTIRANJE.KATEGORIJA (naziv) VALUES ('TELEKOMUNIKACIJSKI');

CREATE TABLE EVIDENTIRANJE.PRIORITET(
prioritet_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
naziv VARCHAR(100) NOT NULL,
CONSTRAINT prioritet_id_pk PRIMARY KEY (prioritet_id)
);

INSERT INTO EVIDENTIRANJE.PRIORITET (naziv) VALUES ('Visoki');
INSERT INTO EVIDENTIRANJE.PRIORITET (naziv) VALUES ('Srednji');
INSERT INTO EVIDENTIRANJE.PRIORITET (naziv) VALUES ('Niski');

CREATE TABLE EVIDENTIRANJE.ADRESA(
adresa_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
drzava VARCHAR(30) NOT NULL,
grad INTEGER NOT NULL,/*greška nije INTEGER nego VARCHAR(30) - promjena izvršena*/
ulica INTEGER NOT NULL, /*greška nije INTEGER nego VARCHAR(30) - promjena izvršena*/
kucni_broj INTEGER NOT NULL,
korisnik_id INTEGER NOT NULL,
CONSTRAINT adresa_id_pk PRIMARY KEY (adresa_id),
CONSTRAINT korisnik_id_fk FOREIGN KEY (korisnik_id) REFERENCES EVIDENTIRANJE.KORISNIK(korisnik_id)
);

CREATE TABLE EVIDENTIRANJE.PRISTUP(
pristup_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
korisnicko_ime VARCHAR(10) NOT NULL,
lozinka VARCHAR(8), /*greška nije VARCHAR(8) nego CHAR(8) NOT NULL*/
korisnik_id INTEGER NOT NULL,
CONSTRAINT pristup_id_pk PRIMARY KEY(pristup_id),
CONSTRAINT pristup_korisnik_id_fk FOREIGN KEY (korisnik_id) REFERENCES EVIDENTIRANJE.KORISNIK(korisnik_id)
);

CREATE TABLE EVIDENTIRANJE.INCIDENT_POÈETAK(
broj_naloga INTEGER NOT NULL,
pocetak_d DATE NOT NULL,
pocetak_t TIME NOT NULL,
zahvaceni_uredaji VARCHAR(50) NOT NULL,
napomena VARCHAR(200),
incident_rjesava VARCHAR(50) NOT NULL,
rjesen BOOLEAN NOT NULL,
korisnik_id INTEGER NOT NULL,
vrsta_id INTEGER NOT NULL,
prioritet_id INTEGER NOT NULL,
kategorija_id INTEGER NOT NULL,
CONSTRAINT broj_naloga_pk PRIMARY KEY (broj_naloga),
CONSTRAINT pocetak_korisnik_id_fk FOREIGN KEY (korisnik_id) REFERENCES EVIDENTIRANJE.KORISNIK(korisnik_id),
CONSTRAINT vrsta_id_fk FOREIGN KEY (vrsta_id) REFERENCES EVIDENTIRANJE.VRSTA(vrsta_id),
CONSTRAINT prioritet_id_fk FOREIGN KEY (prioritet_id) REFERENCES EVIDENTIRANJE.PRIORITET(prioritet_id),
CONSTRAINT kategorija_id FOREIGN KEY (kategorija_id) REFERENCES EVIDENTIRANJE.KATEGORIJA(kategorija_id)
);

CREATE TABLE EVIDENTIRANJE.INCIDENT_KRAJ(
kraj_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
kraj_d DATE NOT NULL,
kraj_t TIME NOT NULL,
broj_naloga INTEGER NOT NULL,
CONSTRAINT kraj_id_pk PRIMARY KEY (kraj_id),
CONSTRAINT broj_naloga_fk FOREIGN KEY (broj_naloga) REFERENCES EVIDENTIRANJE.INCIDENT_POÈETAK(broj_naloga)
);

CREATE TABLE EVIDENTIRANJE.INCIDENT_TRAJANJE(
trajanje_id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
trajanje VARCHAR(50) NOT NULL,
broj_naloga INTEGER NOT NULL,
kraj_id INTEGER NOT NULL,
CONSTRAINT trajanje_id_pk PRIMARY KEY (trajanje_id),
CONSTRAINT trajanje_broj_naloga_fk FOREIGN KEY (broj_naloga) REFERENCES EVIDENTIRANJE.INCIDENT_POÈETAK(broj_naloga),
CONSTRAINT kraj_id_fk FOREIGN KEY (kraj_id) REFERENCES EVIDENTIRANJE.INCIDENT_KRAJ(kraj_id)
);





